### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by ghost** [icedream/NPSharp#1]
Can't compile? Please provide extra detail in.

Error occurred: System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Directory.GetParent(String path)
   at GitVersion.ConfigurationProvider.GetConfigFilePath(String gitDirectory) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\Configuration\ConfigurationProvider.cs:line 51
   at GitVersion.ConfigurationProvider.Provide(String gitDirectory, IFileSystem fileSystem) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\Configuration\ConfigurationProvider.cs:line 13
   at GitVersionTask.WriteVersionInfoToBuildLog.InnerExecute() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionTask\WriteVersionInfoToBuildLog.cs:line 54
   at GitVersionTask.WriteVersionInfoToBuildLog.Execute() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionTask\WriteVersionInfoToBuildLog.cs:line 31    NPSharp.Client

**Comment by icedream** [comment]
I suspect you downloaded the source via the "download" option offered by GitHub instead of cloning the source code? Try cloning the source code using Git instead and then let me know if it worked.

**Comment by ghost** [comment]
Got it working already.. Trying to compile the core now. But its much
harder then I thought it was.
Op 11 jun. 2016 14:46 schreef "Carl Kittelberger" <notifications@github.com

**Comment by icedream** [comment]
What was the issue exactly so maybe I can improve the code? Thanks in advance.

**Comment by ghost** [comment]
I believe it was my own stupid fault. I haven't changed any code lines.
